"""
HLER Lab - DataAuditAgent
Stage: DATA_AUDIT

Audits available datasets before question formulation.
Produces a dataset inventory report.
"""

from __future__ import annotations

import os
from pathlib import Path

from agents.base_agent import BaseAgent
from config.run_state import PipelineStage, RunState

RAW_DATA_DIR = "data/raw"
PROCESSED_DATA_DIR = "data/processed"
REPORT_PATH = "outputs/data_audit_report.md"


class DataAuditAgent(BaseAgent):
    """
    Audits available datasets and produces an inventory report.

    This agent runs before any research question is selected, giving
    the Human PI an informed basis for choosing a research direction.
    """

    stage = PipelineStage.DATA_AUDIT

    def run(self, state: RunState, **kwargs) -> RunState:
        self._assert_stage(state)
        self._log(state, "Starting data audit.")

        raw_files = self._list_files(RAW_DATA_DIR)
        processed_files = self._list_files(PROCESSED_DATA_DIR)

        report = self._build_report(raw_files, processed_files)
        self._write_report(report)
        state.register_artifact("data_audit_report", REPORT_PATH)

        self._log(
            state,
            f"Data audit complete. Found {len(raw_files)} raw file(s) and "
            f"{len(processed_files)} processed file(s). Report: {REPORT_PATH}",
        )
        state.advance_stage()
        return state

    # ------------------------------------------------------------------ #
    # Internal helpers                                                     #
    # ------------------------------------------------------------------ #

    def _list_files(self, directory: str) -> list[dict]:
        """Return metadata for each file in a directory."""
        results = []
        path = Path(directory)
        if not path.exists():
            return results
        for f in sorted(path.iterdir()):
            if f.is_file() and not f.name.startswith("."):
                results.append({
                    "name": f.name,
                    "size_kb": round(f.stat().st_size / 1024, 2),
                    "path": str(f),
                })
        return results

    def _build_report(
        self,
        raw_files: list[dict],
        processed_files: list[dict],
    ) -> str:
        lines = [
            "# HLER Data Audit Report",
            "",
            "## Raw Datasets (`data/raw/`)",
            "",
        ]
        if raw_files:
            lines.append("| File | Size (KB) |")
            lines.append("|------|-----------|")
            for f in raw_files:
                lines.append(f"| {f['name']} | {f['size_kb']} |")
        else:
            lines.append("_No raw datasets found._")

        lines += [
            "",
            "## Processed Datasets (`data/processed/`)",
            "",
        ]
        if processed_files:
            lines.append("| File | Size (KB) |")
            lines.append("|------|-----------|")
            for f in processed_files:
                lines.append(f"| {f['name']} | {f['size_kb']} |")
        else:
            lines.append("_No processed datasets found._")

        lines += [
            "",
            "---",
            "_Generated by DataAuditAgent (HLER Lab)_",
        ]
        return "\n".join(lines)

    def _write_report(self, report: str) -> None:
        os.makedirs(os.path.dirname(REPORT_PATH), exist_ok=True)
        with open(REPORT_PATH, "w", encoding="utf-8") as f:
            f.write(report)
