"""
HLER Lab - EconometricsAgent
Stage: ANALYSIS

Produces regressions, summary statistics, and visualizations.
Pauses at GATE_IDENTIFICATION_APPROVAL for Human PI to confirm
the causal identification strategy.
"""

from __future__ import annotations

import os

from agents.base_agent import BaseAgent
from config.run_state import PipelineStage, RunState

TABLES_DIR = "outputs/tables"
FIGURES_DIR = "outputs/figures"


class EconometricsAgent(BaseAgent):
    """
    Runs econometric analysis for the selected research question.

    Produces:
    - Summary statistics table
    - Main regression table (OLS with HC3 robust SEs)
    - Identification strategy memo for human review

    Human gate: GATE_IDENTIFICATION_APPROVAL
    The Human PI must confirm the identification strategy before results
    are finalized.
    """

    stage = PipelineStage.ANALYSIS

    def run(self, state: RunState, **kwargs) -> RunState:
        self._assert_stage(state)
        self._log(state, "Starting econometric analysis.")

        os.makedirs(TABLES_DIR, exist_ok=True)
        os.makedirs(FIGURES_DIR, exist_ok=True)

        self._run_summary_statistics(state)
        identification_memo = self._propose_identification_strategy(state)

        print("\n--- Proposed Identification Strategy ---")
        print(identification_memo)
        print()

        selection = state.await_human_gate(
            gate="GATE_IDENTIFICATION_APPROVAL",
            prompt=(
                "Please review the proposed causal identification strategy above.\n"
                "Enter 'approve' to proceed, or describe any changes required."
            ),
        )

        if selection.strip().lower() != "approve":
            self._log(
                state,
                f"Identification strategy revision requested: {selection}",
            )
            state.metadata["identification_revision"] = selection

        self._run_main_regression(state)
        self._log(state, "Econometric analysis complete.")
        state.advance_stage()
        return state

    # ------------------------------------------------------------------ #
    # Internal helpers                                                     #
    # ------------------------------------------------------------------ #

    def _run_summary_statistics(self, state: RunState) -> None:
        """Generate summary statistics table (stub)."""
        table_path = os.path.join(TABLES_DIR, "summary_statistics.csv")
        with open(table_path, "w", encoding="utf-8") as f:
            f.write("variable,n,mean,sd,min,max\n")
            f.write("# Populate with actual data\n")
        tex_path = os.path.join(TABLES_DIR, "summary_statistics.tex")
        with open(tex_path, "w", encoding="utf-8") as f:
            f.write("% Summary statistics table — generated by EconometricsAgent\n")
        state.register_artifact("summary_statistics_csv", table_path)
        state.register_artifact("summary_statistics_tex", tex_path)
        self._log(state, f"Summary statistics written to {table_path}")

    def _propose_identification_strategy(self, state: RunState) -> str:
        """
        Propose a causal identification strategy based on the research question.

        In production, this would analyze the data and research question to
        suggest an appropriate strategy (OLS, IV, DiD, RDD, etc.).
        """
        question = state.research_question or ""
        strategy = (
            f"Research Question: {question}\n\n"
            "Proposed Strategy: OLS with heteroskedasticity-robust standard errors (HC3)\n"
            "  - Main specification: Y = α + βX + γZ + ε\n"
            "  - Standard errors: HC3 robust\n"
            "  - Robustness checks: subsample analysis, alternative controls\n\n"
            "Identification Assumptions:\n"
            "  1. Conditional independence given observable controls\n"
            "  2. No unmeasured confounders correlated with X\n\n"
            "Limitations:\n"
            "  - OLS estimates association, not necessarily causal effect\n"
            "  - IV instruments not yet identified (flag for human review)\n"
        )
        memo_path = os.path.join(TABLES_DIR, "identification_memo.md")
        with open(memo_path, "w", encoding="utf-8") as f:
            f.write("# Identification Strategy Memo\n\n")
            f.write(strategy)
        state.register_artifact("identification_memo", memo_path)
        return strategy

    def _run_main_regression(self, state: RunState) -> None:
        """Run main regression and save output tables (stub)."""
        table_path = os.path.join(TABLES_DIR, "main_regression.csv")
        with open(table_path, "w", encoding="utf-8") as f:
            f.write("variable,coef,se,t_stat,p_value,ci_lower,ci_upper\n")
            f.write("# Populate with actual regression results\n")
        tex_path = os.path.join(TABLES_DIR, "main_regression.tex")
        with open(tex_path, "w", encoding="utf-8") as f:
            f.write("% Main regression table — generated by EconometricsAgent\n")
        state.register_artifact("main_regression_csv", table_path)
        state.register_artifact("main_regression_tex", tex_path)
        self._log(state, f"Main regression table written to {table_path}")
