"""
HLER Lab - QuestionAgent
Stage: QUESTIONING

Generates candidate research questions based on the data audit.
Pauses at GATE_QUESTION_SELECTION for Human PI to select one.
"""

from __future__ import annotations

import os

from agents.base_agent import BaseAgent
from config.run_state import PipelineStage, RunState

CANDIDATES_REPORT = "outputs/question_candidates.md"

QUESTION_TEMPLATES = [
    "What is the effect of {treatment} on {outcome} using {dataset}?",
    "How does {treatment} moderate the relationship between {mediator} and {outcome}?",
    "Do returns to {treatment} vary by {heterogeneity_dimension} in {dataset}?",
    "What is the causal effect of {treatment} on {outcome} in the {context} context?",
]


class QuestionAgent(BaseAgent):
    """
    Generates candidate research questions and presents them to the Human PI.

    Human gate: GATE_QUESTION_SELECTION
    The agent pauses and waits for the Human PI to select a question.
    """

    stage = PipelineStage.QUESTIONING

    def run(self, state: RunState, **kwargs) -> RunState:
        self._assert_stage(state)
        self._log(state, "Generating candidate research questions.")

        candidates = self._generate_candidates(state)
        report = self._build_report(candidates)
        self._write_report(report)
        state.register_artifact("question_candidates", CANDIDATES_REPORT)

        self._log(
            state,
            f"Generated {len(candidates)} candidate question(s). "
            "Waiting for human selection.",
        )

        print("\n--- Candidate Research Questions ---")
        for i, q in enumerate(candidates, 1):
            print(f"  [{i}] {q}")
        print()

        selection = state.await_human_gate(
            gate="GATE_QUESTION_SELECTION",
            prompt=(
                "Please select a research question from the candidates above.\n"
                "Enter the number (e.g. '1') or type your own question."
            ),
            options=candidates,
        )

        # Resolve selection to actual question text
        try:
            idx = int(selection) - 1
            if 0 <= idx < len(candidates):
                question = candidates[idx]
            else:
                question = selection
        except ValueError:
            question = selection

        state.research_question = question
        self._log(state, f"Research question selected: {question}")
        state.advance_stage()
        return state

    # ------------------------------------------------------------------ #
    # Internal helpers                                                     #
    # ------------------------------------------------------------------ #

    def _generate_candidates(self, state: RunState) -> list[str]:
        """
        Generate candidate research questions.

        In production, this would use the data audit report and an LLM
        to propose data-driven questions. Here we provide illustrative
        examples aligned with HLER research scope.
        """
        return [
            "What is the effect of education on wages using the available labor dataset?",
            "How does health status affect labor market participation?",
            "Do returns to schooling vary by region or household income level?",
            "What is the causal effect of agricultural extension services on crop yields?",
            "How do behavioral nudges affect savings decisions among low-income households?",
        ]

    def _build_report(self, candidates: list[str]) -> str:
        lines = [
            "# HLER Research Question Candidates",
            "",
            "The following questions were generated based on the data audit report.",
            "The Human PI must select one to proceed.",
            "",
            "## Candidates",
            "",
        ]
        for i, q in enumerate(candidates, 1):
            lines.append(f"{i}. {q}")
        lines += [
            "",
            "---",
            "_Generated by QuestionAgent (HLER Lab)_",
        ]
        return "\n".join(lines)

    def _write_report(self, report: str) -> None:
        os.makedirs(os.path.dirname(CANDIDATES_REPORT), exist_ok=True)
        with open(CANDIDATES_REPORT, "w", encoding="utf-8") as f:
            f.write(report)
