"""
HLER Lab - ReviewerAgent
Stage: REVIEW

Evaluates the manuscript draft for novelty, identification validity,
clarity, and policy relevance. Produces a structured review report.
"""

from __future__ import annotations

import os

from agents.base_agent import BaseAgent
from config.run_state import PipelineStage, RunState

REVIEW_REPORT_PATH = "outputs/review_report.md"

REVIEW_DIMENSIONS = [
    "novelty",
    "identification_validity",
    "clarity",
    "policy_relevance",
    "data_quality",
    "robustness",
]


class ReviewerAgent(BaseAgent):
    """
    Evaluates the manuscript draft and produces a structured review.

    Review dimensions:
    - Novelty: Is the research question original?
    - Identification validity: Is the causal claim defensible?
    - Clarity: Is the paper clearly written and well-organized?
    - Policy relevance: Are there actionable implications?
    - Data quality: Are the data appropriate for the question?
    - Robustness: Are the findings robust to alternative specifications?

    This agent does NOT have a human gate — the review is fully automated.
    The human gate is at the FINAL_APPROVAL stage (handled by Orchestrator).
    """

    stage = PipelineStage.REVIEW

    def run(self, state: RunState, **kwargs) -> RunState:
        self._assert_stage(state)
        self._log(state, "Starting manuscript review.")

        manuscript_path = state.artifacts.get("manuscript_draft", "")
        manuscript = self._load_manuscript(manuscript_path)

        scores = self._evaluate(state, manuscript)
        report = self._build_report(state, scores)
        self._write_report(report)
        state.register_artifact("review_report", REVIEW_REPORT_PATH)

        overall = sum(scores.values()) / len(scores)
        self._log(
            state,
            f"Review complete. Overall score: {overall:.1f}/5.0. "
            f"Report: {REVIEW_REPORT_PATH}",
        )
        state.advance_stage()
        return state

    # ------------------------------------------------------------------ #
    # Internal helpers                                                     #
    # ------------------------------------------------------------------ #

    def _load_manuscript(self, path: str) -> str:
        if path and os.path.exists(path):
            with open(path, encoding="utf-8") as f:
                return f.read()
        return ""

    def _evaluate(self, state: RunState, manuscript: str) -> dict[str, float]:
        """
        Evaluate the manuscript across all review dimensions.

        In production, this would use an LLM to produce structured
        evaluation scores and comments. Here we return placeholder scores.
        """
        return {dim: 3.0 for dim in REVIEW_DIMENSIONS}

    def _build_report(self, state: RunState, scores: dict[str, float]) -> str:
        overall = sum(scores.values()) / len(scores)
        lines = [
            "# HLER Manuscript Review Report",
            "",
            f"**Research Question**: {state.research_question or '(not set)'}",
            f"**Dataset**: {state.active_dataset or '(none)'}",
            f"**Run ID**: {state.run_id}",
            "",
            "## Scores",
            "",
            "| Dimension | Score (1–5) | Notes |",
            "|-----------|------------|-------|",
        ]
        for dim, score in scores.items():
            label = dim.replace("_", " ").title()
            lines.append(f"| {label} | {score:.1f} | _[Reviewer comments]_ |")

        lines += [
            "",
            f"**Overall Score**: {overall:.1f} / 5.0",
            "",
            "## Summary",
            "",
            "_[Automated review summary — Human PI should read carefully before final approval]_",
            "",
            "## Recommendation",
            "",
            (
                "✅ **Accept with minor revisions**"
                if overall >= 3.5
                else "⚠️ **Major revisions required**"
            ),
            "",
            "---",
            "_Generated by ReviewerAgent (HLER Lab)_",
            "_Final publication decision requires explicit Human PI approval._",
        ]
        return "\n".join(lines)

    def _write_report(self, report: str) -> None:
        os.makedirs(os.path.dirname(REVIEW_REPORT_PATH), exist_ok=True)
        with open(REVIEW_REPORT_PATH, "w", encoding="utf-8") as f:
            f.write(report)
